"""SQLAlchemy ORM models.

All models inherit from :class:`app.models.base.Base`. Everything is re-exported
here so Alembic's ``env.py`` can ``from app.models import *`` and see the full
metadata for autogenerate.

Migrations are hand-written rather than autogenerated: partitioned tables,
expression indexes, and the ``uuidv7()`` function are all things Alembic's
autogenerate does not model. Autogenerate is used as a *drift check*
(``tests/integration/test_schema.py``), not as the source of migrations.
"""

from app.models.base import Base, TimestampMixin
from app.models.enums import (
    JobStatus,
    LeagueProvider,
    ModelStatus,
    Position,
    RecommendationKind,
    SyncStatus,
)
from app.models.explanation import Explanation
from app.models.game import Game, GameOdds, GameWeather
from app.models.job import Job, SyncError
from app.models.league import (
    League,
    LeagueMembership,
    Lineup,
    Matchup,
    RosterEntry,
    Team,
    Transaction,
)
from app.models.player import InjuryReport, NflTeam, Player, PlayerExternalId
from app.models.prediction import ModelVersion, Prediction, PredictionHistory
from app.models.recommendation import Recommendation, TradeAnalysis
from app.models.simulation import SimulationResult
from app.models.stats import FeatureStore, WeeklyStats
from app.models.user import User

__all__ = [
    "Base",
    "Explanation",
    "FeatureStore",
    "Game",
    "GameOdds",
    "GameWeather",
    "InjuryReport",
    "Job",
    "JobStatus",
    "League",
    "LeagueMembership",
    "LeagueProvider",
    "Lineup",
    "Matchup",
    "ModelStatus",
    "ModelVersion",
    "NflTeam",
    "Player",
    "PlayerExternalId",
    "Position",
    "Prediction",
    "PredictionHistory",
    "Recommendation",
    "RecommendationKind",
    "RosterEntry",
    "SimulationResult",
    "SyncError",
    "SyncStatus",
    "Team",
    "TimestampMixin",
    "TradeAnalysis",
    "Transaction",
    "User",
    "WeeklyStats",
]
