"""Declarative base and shared column helpers for all ORM models.

Conventions enforced here:

* A metadata naming convention so that autogenerated constraints get stable,
  predictable names. Hand-written migrations still name constraints explicitly
  (matching RFC Section 11), but the convention keeps future `--autogenerate`
  output from inventing names that drift from the deployed schema.
* Timestamps are always ``TIMESTAMPTZ`` with a server-side ``now()`` default, so
  a row inserted by Alembic, a raw SQL backfill, or the ORM all agree.
* Scoring arithmetic uses ``NUMERIC``/``Decimal``. See RFC 11.1 principle 6.
"""

from __future__ import annotations

import datetime as dt
from typing import Any

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

NAMING_CONVENTION: dict[str, str] = {
    "ix": "idx_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for all ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    def __repr__(self) -> str:  # pragma: no cover - debugging affordance only
        pk: dict[str, Any] = {
            col.name: getattr(self, col.name) for col in self.__table__.primary_key
        }
        rendered = ", ".join(f"{k}={v!r}" for k, v in pk.items())
        return f"<{type(self).__name__} {rendered}>"


def utc_now_column(*, onupdate: bool = False) -> Mapped[dt.datetime]:
    """A ``TIMESTAMPTZ NOT NULL DEFAULT now()`` column."""
    return mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        server_onupdate=func.now() if onupdate else None,
    )


class TimestampMixin:
    """``created_at`` / ``updated_at`` pair used by most mutable entities."""

    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
